In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(1,50,1000000)

In [3]:
arr1

array([20,  2,  6, ...,  7, 31,  4])

In [7]:
%%timeit 
sum(arr1)

40.5 ms ± 933 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%%timeit 
np.sum(arr1)

204 µs ± 9.61 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
%%timeit
min(arr1)

32.4 ms ± 787 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%%timeit
np.min(arr1)

81.3 µs ± 1.6 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
np.sum(arr1)

25002886

In [12]:
np.min(arr1)

1

In [13]:
np.max(arr1)

49

In [14]:
np.sum(arr1)

25002886

In [16]:
arr2 = np.arange(1,25).reshape(6,4)

In [17]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [18]:
arr2.sum()

300

In [22]:
arr2.sum(axis=0) #Column-Wise

array([66, 72, 78, 84])

In [24]:
arr2.sum(axis=1) #Row-Wise

array([10, 26, 42, 58, 74, 90])

In [26]:
arr2.min(axis =0) #Column-Wise

array([1, 2, 3, 4])

In [27]:
arr2.min(axis=1) #Row-Wise

array([ 1,  5,  9, 13, 17, 21])

In [28]:
arr2.std()

6.922186552431729

In [29]:
arr2.mean()

12.5

In [32]:
arr2.var()

47.916666666666664

In [33]:
np.median(arr2)

12.5

In [34]:
np.percentile(arr1,50)

25.0

In [35]:
arr2 = np.array([np.nan,6,7])

In [36]:
arr2

array([nan,  6.,  7.])

In [37]:
arr2.sum()

nan

In [39]:
np.nansum(arr2)

13.0

---