In [1]:
import numpy as np

In [2]:
np.random.seed(5)

In [3]:
arr1 = np.random.randint(1,1000,50)

In [4]:
arr1

array([868, 207, 702, 999, 119, 401,  74,   9, 741, 744, 959, 412, 625,
       671, 721, 520, 205, 912, 114, 438,  81,  28,  45, 206, 716,  66,
       432, 543, 981,  87, 638, 147, 255, 378, 650, 363,  42, 447, 898,
       211, 104, 145, 975,   6, 827, 769, 977, 901, 111, 677])

In [6]:
arr1[0]

868

In [7]:
arr1.shape

(50,)

In [8]:
arr1.dtype

dtype('int32')

In [9]:
arr1.size

50

In [10]:
arr1.ndim

1

In [12]:
arr1[0:10:2]

array([868, 702, 119,  74, 741])

In [13]:
arr1 = arr1.reshape([5,10])

In [14]:
arr1

array([[868, 207, 702, 999, 119, 401,  74,   9, 741, 744],
       [959, 412, 625, 671, 721, 520, 205, 912, 114, 438],
       [ 81,  28,  45, 206, 716,  66, 432, 543, 981,  87],
       [638, 147, 255, 378, 650, 363,  42, 447, 898, 211],
       [104, 145, 975,   6, 827, 769, 977, 901, 111, 677]])

In [15]:
arr1.ndim

2

In [16]:
arr1[0,1]

207

In [19]:
arr1[0:5,2:4]

array([[702, 999],
       [625, 671],
       [ 45, 206],
       [255, 378],
       [975,   6]])

In [20]:
arr1[:,1]

array([207, 412,  28, 147, 145])

In [22]:
arr1[1,:]

array([959, 412, 625, 671, 721, 520, 205, 912, 114, 438])

In [31]:
arr2 = np.array([1,2,3,4,5])
arr2, arr2.shape

(array([1, 2, 3, 4, 5]), (5,))

In [35]:
arr2[:,np.newaxis],arr2[:,np.newaxis].shape #column vector

(array([[1],
        [2],
        [3],
        [4],
        [5]]),
 (5, 1))

In [34]:
arr2[np.newaxis,:],arr2[np.newaxis,:].shape   #row vector

(array([[1, 2, 3, 4, 5]]), (1, 5))

In [36]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.array([7,8,9])

In [37]:
a4  = np.concatenate([a1,a2])

In [38]:
a4

array([1, 2, 3, 4, 5, 6])

In [42]:
np.concatenate([a1,a2,a3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

In [44]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([grid,grid],axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
a1

array([1, 2, 3])

In [49]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.vstack((a1,grid))

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [57]:
np.hstack(([[1],[2]],grid))

array([[1, 1, 2, 3],
       [2, 4, 5, 6]])

In [58]:
x =np.array([1,2,3,4,5,6,7,8,9])

In [59]:
np.split(x,indices_or_sections=[1])

[array([1]), array([2, 3, 4, 5, 6, 7, 8, 9])]

In [60]:
np.split(x,indices_or_sections=[1,3,8])

[array([1]), array([2, 3]), array([4, 5, 6, 7, 8]), array([9])]

### Split N leads to N+1 Subarrays

In [61]:
np.split(x,indices_or_sections=[2,4,6,8])

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]

In [62]:
grid = np.arange(16).reshape((4, 4))

In [63]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
np.hsplit(grid,indices_or_sections=[1,2])

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [65]:
np.vsplit(grid,indices_or_sections=[1,2])

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

---