In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(1000)

In [19]:
x = rng.integers(1,100,10)

In [20]:
x

array([30, 19, 50, 28, 26, 75, 19, 55,  1, 86], dtype=int64)

In [21]:
x[[3,8,9]]

array([28,  1, 86], dtype=int64)

In [22]:
ind = np.array([[2,3],[5,6]])

In [23]:
x[ind]

array([[50, 28],
       [75, 19]], dtype=int64)

### Copy instead of View

In [24]:
y = x.reshape(2,5).copy()

In [25]:
y

array([[30, 19, 50, 28, 26],
       [75, 19, 55,  1, 86]], dtype=int64)

In [26]:
y[0,0]=1

In [27]:
y

array([[ 1, 19, 50, 28, 26],
       [75, 19, 55,  1, 86]], dtype=int64)

In [28]:
x

array([30, 19, 50, 28, 26, 75, 19, 55,  1, 86], dtype=int64)

In [31]:
row = np.array([0,1])
column = np.array([1,3])

In [33]:
y[row,column] #y[0,1] & y[1,3]

array([19,  1], dtype=int64)

In [34]:
row[:,np.newaxis]

array([[0],
       [1]])

In [36]:
y[row[:,np.newaxis],column] #y[0,1] y[0,3] & y[1,1] y[1,3]

array([[19, 28],
       [19,  1]], dtype=int64)

In [78]:
z = np.random.randint(1,1000,15).reshape(3,5)

In [79]:
z

array([[894, 348, 416, 477, 967],
       [765, 317,  36, 598, 335],
       [606, 448, 463, 429, 703]])

In [80]:
z[1,[1,3,4]] #2nd row, 2nd 4th and 5th element

array([317, 598, 335])

In [81]:
z[1:,[1,2,3]]

array([[317,  36, 598],
       [448, 463, 429]])

In [82]:
mask = np.array([True,False,False,True,False])

In [83]:
z[1,mask]

array([765, 598])

In [84]:
z[1:3,mask]

array([[765, 598],
       [606, 429]])

In [85]:
data = np.random.normal(size=(50,2))

In [86]:
data

array([[ 1.73938826,  0.27597599],
       [ 1.04476114, -1.69459836],
       [ 0.40835045,  0.31390926],
       [ 0.73933085, -1.11422994],
       [ 0.8198466 ,  0.29355833],
       [ 0.07025879,  0.0726009 ],
       [-0.59505126, -0.47949741],
       [-0.26890129, -0.2767831 ],
       [ 0.70720563, -0.36437136],
       [-0.1353698 , -0.26321732],
       [ 1.76245054, -0.31598902],
       [ 0.0104163 ,  0.65110077],
       [ 1.1341289 ,  0.10941766],
       [-0.0622113 , -0.29137146],
       [ 0.58402231, -0.07381776],
       [ 0.01164809,  1.12790828],
       [-0.79655263,  1.0631337 ],
       [ 0.46803887, -0.5918224 ],
       [-0.32783334, -0.23303282],
       [ 0.60284131, -1.1290296 ],
       [ 0.72940359,  2.30010189],
       [-0.23905799, -0.7054006 ],
       [ 1.08519841, -0.60094883],
       [ 1.84764316, -0.00346277],
       [-0.34978558,  0.63777246],
       [ 0.91567177,  0.01152187],
       [ 0.14574936,  0.21908638],
       [-0.82445229,  0.22957454],
       [ 1.58492497,

In [87]:
indices = np.random.choice(data.shape[0],10,replace = False)

In [88]:
indices

array([47,  3, 30, 21, 17, 13, 46, 36,  4, 27])

In [89]:
random_10_pts = data[indices]

In [90]:
random_10_pts

array([[-1.03149895, -0.24790786],
       [ 0.73933085, -1.11422994],
       [-0.7502651 , -1.3405841 ],
       [-0.23905799, -0.7054006 ],
       [ 0.46803887, -0.5918224 ],
       [-0.0622113 , -0.29137146],
       [ 0.43313785, -1.63974983],
       [-1.94289599, -0.7122762 ],
       [ 0.8198466 ,  0.29355833],
       [-0.82445229,  0.22957454]])

In [91]:
random_10_pts.shape

(10, 2)

In [92]:
z

array([[894, 348, 416, 477, 967],
       [765, 317,  36, 598, 335],
       [606, 448, 463, 429, 703]])

In [93]:
z[1,[0,2,4]]

array([765,  36, 335])

In [94]:
z

array([[894, 348, 416, 477, 967],
       [765, 317,  36, 598, 335],
       [606, 448, 463, 429, 703]])

In [95]:
z[1,[0,2,4]] += 1

In [96]:
z

array([[894, 348, 416, 477, 967],
       [766, 317,  37, 598, 336],
       [606, 448, 463, 429, 703]])

In [101]:
z[1,[1,1]] =[4,5] # first z[1,1] becomes 4 then z[1,1] becomes 5

In [102]:
z

array([[894, 348, 416, 477, 967],
       [766,   5,  37, 598, 336],
       [606, 448, 463, 429, 703]])

In [103]:
x

array([30, 19, 50, 28, 26, 75, 19, 55,  1, 86], dtype=int64)

In [104]:
x[[1,2,3,4]] += 1

In [105]:
x

array([30, 20, 51, 29, 27, 75, 19, 55,  1, 86], dtype=int64)

In [106]:
x[[1,1,2,2,3]] +=1

In [108]:
x #Note index 1 is added by 1 not by 2 (same for index 2)

array([30, 21, 52, 30, 27, 75, 19, 55,  1, 86], dtype=int64)

In [110]:
np.add.at(x,[1,1,2,2,3],1)

In [112]:
x #Note now index 1 is added by 2 (same for index 2)

array([30, 23, 54, 31, 27, 75, 19, 55,  1, 86], dtype=int64)

---