In [1]:
import numpy as np

In [2]:
list1 = [1,4,5,6,10]

In [3]:
arr1 = np.array(list1)

In [4]:
arr1

array([ 1,  4,  5,  6, 10])

In [8]:
arr2 = np.array(list1,dtype='float32')

In [6]:
arr2

array([ 1.,  4.,  5.,  6., 10.], dtype=float32)

In [9]:
list2 = [1,3.5,True,'Thomas']

In [10]:
arr3 = np.array(list2)

In [11]:
arr3

array(['1', '3.5', 'True', 'Thomas'], dtype='<U32')

### Array Creational Methods

In [13]:
z_arr = np.zeros(shape=(10,),dtype ='int32')

In [14]:
z_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
z_arr1 = np.zeros(shape=(10,3),dtype ='int32')

In [16]:
z_arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
o_arr = np.ones(shape=(5,),dtype='int64')

In [18]:
o_arr

array([1, 1, 1, 1, 1], dtype=int64)

In [19]:
eye_arr = np.eye(N=3)

In [20]:
eye_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
five_arr = np.full(shape=(3,2),fill_value =5)

In [22]:
five_arr

array([[5, 5],
       [5, 5],
       [5, 5]])

In [25]:
arange_arr = np.arange(start = 1, stop = 22, step = 2 )

In [26]:
arange_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [27]:
linspace_arr = np.linspace(start = 1,stop = 2,num = 10)

In [28]:
linspace_arr

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [30]:
linspace_arr[0:len(linspace_arr)-1]-linspace_arr[1:]

array([-0.11111111, -0.11111111, -0.11111111, -0.11111111, -0.11111111,
       -0.11111111, -0.11111111, -0.11111111, -0.11111111])

In [31]:
emp_arr = np.empty(shape=(20,0))

In [32]:
emp_arr

array([], shape=(20, 0), dtype=float64)

In [33]:
emp_arr[0]

array([], dtype=float64)

In [34]:
random_arr = np.random.random(size=10).reshape(2,5)

In [35]:
random_arr

array([[0.361746  , 0.01776077, 0.75268761, 0.44882675, 0.606269  ],
       [0.68436572, 0.94493087, 0.34316055, 0.08411241, 0.75730211]])

In [38]:
randint_arr = np.random.randint(low=1,high=5,size=(10,1))

In [39]:
randint_arr

array([[1],
       [4],
       [2],
       [2],
       [3],
       [1],
       [4],
       [1],
       [1],
       [1]])

In [40]:
normal_arr = np.random.normal(loc=0,scale=1.0,size=(50,))

In [41]:
normal_arr

array([ 0.57130496, -1.60060117, -0.23829985,  1.60521299,  0.213598  ,
        0.03406841, -0.96891133,  0.04183823, -1.69472495,  0.22301753,
       -0.37396437, -0.15938182, -0.13871037,  0.97500201,  0.57118713,
        0.81377603, -0.68419264, -0.48288334, -1.15716458,  1.3091836 ,
       -0.40010085, -0.64607635, -1.05958471, -0.38944878, -0.47596141,
        0.52970667, -1.06845522,  0.06772669, -0.64736625,  1.55827821,
       -0.04651011, -1.19183967, -0.86642381,  1.92050381, -0.61407761,
       -1.05317467,  1.03694289, -0.66863012, -1.39273836, -1.11676649,
        0.18693179,  0.37799606, -2.28847833, -0.13135198,  1.02920418,
        1.13554929,  0.24985061,  0.98995831, -0.28962723, -0.12462319])

---