In [1]:
import numpy as np

In [3]:
from vega_datasets import data

In [4]:
rainfall_mm = np.array(data.seattle_weather().set_index('date')['precipitation']['2015'])

In [5]:
rainfall_mm

array([ 0. ,  1.5,  0. , 10.2,  8.1,  0. ,  0. ,  0. ,  0.3,  5.8,  1.5,
        0. ,  0. ,  0. ,  9.7,  0. , 26.2, 21.3,  0.5,  0. ,  0. ,  0.8,
        5.8,  0.5,  0. ,  0. ,  0.8,  0. ,  0. ,  0. ,  0. ,  1.5,  7.4,
        1.3,  8.4, 26.2, 17.3, 23.6,  3.6,  6.1,  0.3,  0. ,  1. ,  0. ,
        0.3,  0. ,  0. ,  0. ,  0. ,  4.6,  0.8,  0. ,  0. ,  0. ,  0. ,
        4.1,  9.4, 18.3,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0.8,  2.5,  0. ,  2. , 17. , 55.9,  1. ,  0.8,  0. ,
        0. ,  4.1,  3.8,  1. ,  8.1,  7.6,  5.1,  0. ,  1. ,  0. ,  0. ,
        1.8,  1. ,  5.1,  0. ,  1.5,  0. ,  0. ,  1. ,  0.5,  0. ,  0. ,
       10.9,  0. ,  0. , 14. ,  3.3,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        5.6,  0. ,  3. ,  3.3,  1.3,  0. ,  0.3,  1.8,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  6.1,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  4.3,
        4.1,  0.3,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0

In [6]:
rainfall_mm>0.

array([False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False, False, False,  True, False,  True,  True,
        True, False, False,  True,  True,  True, False, False,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
       False, False, False, False,  True,  True, False, False, False,
       False,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True, False, False,  True,  True, False, False,
        True, False, False,  True,  True, False, False, False, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True, False, False, False, False, False, False,  True, False,
       False, False,

In [8]:
len(rainfall_mm[rainfall_mm>0.])

144

In [14]:
x = np.array([1, 2, 3, 4, 5])

In [15]:
x>1

array([False,  True,  True,  True,  True])

In [16]:
x<1

array([False, False, False, False, False])

In [17]:
x==1

array([ True, False, False, False, False])

In [18]:
x*2 == x**2

array([False,  True, False, False, False])

In [22]:
np.count_nonzero(rainfall_mm==0.)

221

In [23]:
np.count_nonzero(rainfall_mm!=0.)

144

In [24]:
rainy_ = rainfall_mm[rainfall_mm>0.]

In [25]:
rainy_

array([ 1.5, 10.2,  8.1,  0.3,  5.8,  1.5,  9.7, 26.2, 21.3,  0.5,  0.8,
        5.8,  0.5,  0.8,  1.5,  7.4,  1.3,  8.4, 26.2, 17.3, 23.6,  3.6,
        6.1,  0.3,  1. ,  0.3,  4.6,  0.8,  4.1,  9.4, 18.3,  0.8,  2.5,
        2. , 17. , 55.9,  1. ,  0.8,  4.1,  3.8,  1. ,  8.1,  7.6,  5.1,
        1. ,  1.8,  1. ,  5.1,  1.5,  1. ,  0.5, 10.9, 14. ,  3.3,  5.6,
        3. ,  3.3,  1.3,  0.3,  1.8,  6.1,  4.3,  4.1,  0.3,  4.6,  0.5,
        0.5,  0.3,  0.3,  2. ,  7.6, 30.5,  2. ,  0.5, 32.5, 10.2,  5.8,
        0.3,  5.3,  0.3,  0.5,  1. ,  1.8,  4.1,  2. ,  9.9,  0.3, 28.7,
        4.6,  1.3,  0.3,  3.8,  0.3,  8.9,  6.9,  3.3,  1.8, 19.3, 33. ,
       26.2,  0.3,  0.8,  1.3, 12.7,  6.6,  3.3,  1.3,  1.5,  9.9, 33.5,
       47.2, 22.4,  2. , 29.5,  1.5,  2. ,  3. ,  7.1,  0.5, 12.2,  2.5,
       12.7,  2. , 15.7, 11.2, 27.4, 54.1, 13.5,  9.4,  0.3, 16. ,  1.3,
        1.5,  3.6, 21.8, 18.5,  4.3, 27.4,  4.6,  6.1,  2.5,  5.8,  8.6,
        1.5])

In [26]:
rainy_.mean()

7.91111111111111

In [27]:
np.any(rainy_>7.92)

True

In [28]:
rainy_[rainy_>rainy_.mean()]

array([10.2,  8.1,  9.7, 26.2, 21.3,  8.4, 26.2, 17.3, 23.6,  9.4, 18.3,
       17. , 55.9,  8.1, 10.9, 14. , 30.5, 32.5, 10.2,  9.9, 28.7,  8.9,
       19.3, 33. , 26.2, 12.7,  9.9, 33.5, 47.2, 22.4, 29.5, 12.2, 12.7,
       15.7, 11.2, 27.4, 54.1, 13.5,  9.4, 16. , 21.8, 18.5, 27.4,  8.6])

In [29]:
np.all(rainy_>0)

True

In [30]:
random_arr = np.random.randint(1,100,(4,2))

In [31]:
random_arr

array([[79, 24],
       [ 3, 91],
       [58, 39],
       [64, 50]])

In [32]:
np.any(random_arr>50,axis=1)

array([ True,  True,  True,  True])

In [33]:
np.any(random_arr>50,axis=0)

array([ True,  True])

In [35]:
np.count_nonzero(random_arr>0,axis =1)

array([2, 2, 2, 2], dtype=int64)

In [36]:
np.count_nonzero(random_arr>0,axis =0)

array([4, 4], dtype=int64)

In [39]:
np.sum((rainfall_mm>10) & (rainfall_mm<20))

16

In [44]:
print(f"Number days without rain:   {np.sum(rainfall_mm==0)}")
print(f"Number days with rain:    {np.sum(rainfall_mm!=0)}")
print(f"Days with more than 10 mm:  {np.sum(rainfall_mm>10)}")

Number days without rain:   221
Number days with rain:    144
Days with more than 10 mm:  34


In [54]:
rainy = (rainfall_mm>0)

In [55]:
days = np.arange(0,365)

In [56]:
summer = (days>172) & (days<262)

In [50]:
summer

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [57]:
np.median(rainfall_mm[summer])

0.0

In [58]:
np.median(rainfall_mm[rainy])

3.8

In [59]:
np.max(rainfall_mm[rainy])

55.9

In [60]:
np.min(rainfall_mm[rainy])

0.3

In [62]:
x

array([1, 2, 3, 4, 5])

In [63]:
(x>1) and (x>2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
(x>1) & (x>2)

array([False, False,  True,  True,  True])

In [66]:
(x>1) or (x>2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [65]:
(x>1) | (x>2)

array([False,  True,  True,  True,  True])

### and and or perform a single Boolean evaluation on an entire object, while & and | perform multiple Boolean evaluations on the content (the individual bits or bytes) of an object

---