In [1]:
import numpy as np

In [2]:
a = np.arange(0,3)
a

array([0, 1, 2])

In [3]:
a+5

array([5, 6, 7])

In [4]:
np.broadcast_arrays(a,5)

[array([0, 1, 2]), array([5, 5, 5])]

In [5]:
b = np.arange(1,10).reshape(3,3)

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
a+b

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [8]:
np.broadcast_arrays(a,b)

[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])]

In [9]:
e = np.array([1,2,3]).reshape(3,1)

In [10]:
e

array([[1],
       [2],
       [3]])

In [11]:
f = np.array([1,2,3]).reshape(1,3)

In [12]:
f

array([[1, 2, 3]])

In [13]:
e+f

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [14]:
np.broadcast_arrays(e,f)

[array([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]),
 array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])]

In [15]:
M = np.ones((2, 3))
N = np.arange(3)

In [16]:
M,N

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2]))

In [17]:
np.broadcast_arrays(M,N)

[array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0, 1, 2],
        [0, 1, 2]])]

In [18]:
O = np.ones((3, 2))
P = np.arange(3)

In [19]:
np.broadcast_arrays(O,P)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3, 2) and arg 1 with shape (3,).

### Rule 1: Dimensions must be compatible or equal.
The arrays being operated upon must have either the same dimensions or compatible dimensions. Two dimensions are compatible if they are equal or if one of them is 1. If the dimensions are not equal or compatible, an error will be raised.

### Rule 2: Arrays with fewer dimensions are padded with ones on the left.
If the arrays have different numbers of dimensions, the one with fewer dimensions is padded with ones on the left until both arrays have the same number of dimensions.

### Rule 3: Arrays with size 1 in a particular dimension are stretched to match the size of the corresponding dimension in the other array.
If the arrays have the same number of dimensions but different sizes in one or more dimensions, the array with size 1 in a particular dimension is stretched (replicated) to match the size of the corresponding dimension in the other array.

In [26]:
arr1 = np.arange(3)

In [21]:
arr1.shape

(3,)

In [27]:
arr1

array([0, 1, 2])

In [28]:
arr1.reshape(1,3)

array([[0, 1, 2]])

In [32]:
arr2 = arr2.reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
np.broadcast_arrays(arr1,arr2)

[array([[0, 1, 2],
        [0, 1, 2]]),
 array([[0, 1, 2],
        [3, 4, 5]])]

---