In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,1000000)

In [3]:
%%timeit 
for i in range(len(arr1)):
             arr1[i] +=1

180 ms ± 15.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%%timeit
arr2 = arr1 + 1

1.02 ms ± 25.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
np.subtract(arr1+1,arr1)

array([1, 1, 1, ..., 1, 1, 1])

In [7]:
arr2 = arr1*2

In [8]:
arr2-arr1

array([     82,      83,      84, ..., 1000078, 1000079, 1000080])

In [9]:
arr2/2

array([8.200000e+01, 8.300000e+01, 8.400000e+01, ..., 1.000078e+06,
       1.000079e+06, 1.000080e+06])

In [10]:
arr2**8

array([-1069481984,  1834033408,  1627389952, ...,  1556152320,
        -599293696,           0], dtype=int32)

In [12]:
np.log10(np.arange(1,1000))

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ,
       1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126,
       1.20411998, 1.23044892, 1.25527251, 1.2787536 , 1.30103   ,
       1.32221929, 1.34242268, 1.36172784, 1.38021124, 1.39794001,
       1.41497335, 1.43136376, 1.44715803, 1.462398  , 1.47712125,
       1.49136169, 1.50514998, 1.51851394, 1.53147892, 1.54406804,
       1.5563025 , 1.56820172, 1.5797836 , 1.59106461, 1.60205999,
       1.61278386, 1.62324929, 1.63346846, 1.64345268, 1.65321251,
       1.66275783, 1.67209786, 1.68124124, 1.69019608, 1.69897   ,
       1.70757018, 1.71600334, 1.72427587, 1.73239376, 1.74036269,
       1.74818803, 1.75587486, 1.76342799, 1.77085201, 1.77815125,
       1.78532984, 1.79239169, 1.79934055, 1.80617997, 1.81291336,
       1.81954394, 1.8260748 , 1.83250891, 1.83884909, 1.84509804,
       1.85125835, 1.8573325 , 1.86332286, 1.86923172, 1.87506

In [13]:
np.exp(np.log10(np.arange(1,1000)))

array([ 1.        ,  1.35124987,  1.61142883,  1.82587622,  2.01167962,
        2.177443  ,  2.32820606,  2.46721501,  2.59670286,  2.71828183,
        2.83315997,  2.94226957,  3.04634756,  3.14598814,  3.24167853,
        3.33382396,  3.42276574,  3.50879441,  3.59215967,  3.67307797,
        3.75173836,  3.82830705,  3.9029311 ,  3.97574138,  4.04685489,
        4.11637675,  4.18440184,  4.25101608,  4.3162976 ,  4.38031769,
        4.4431416 ,  4.50482921,  4.56543564,  4.62501178,  4.68360468,
        4.741258  ,  4.79801228,  4.8539053 ,  4.90897227,  4.96324614,
        5.01675774,  5.06953598,  5.12160802,  5.17299941,  5.22373422,
        5.27383516,  5.32332367,  5.37222003,  5.42054346,  5.46831215,
        5.51554338,  5.56225357,  5.6084583 ,  5.65417245,  5.69941016,
        5.74418493,  5.78850964,  5.83239658,  5.87585753,  5.91890373,
        5.96154595,  6.00379452,  6.04565934,  6.08714989,  6.1282753 ,
        6.16904433,  6.20946538,  6.24954657,  6.28929569,  6.32

In [14]:
theta = np.linspace(0,1,30)

In [15]:
np.sin(theta)

array([0.        , 0.03447593, 0.06891086, 0.10326387, 0.13749409,
       0.17156085, 0.20542363, 0.23904218, 0.27237651, 0.30538701,
       0.33803442, 0.37027992, 0.40208519, 0.43341239, 0.4642243 ,
       0.49448427, 0.52415632, 0.55320518, 0.58159632, 0.60929597,
       0.6362712 , 0.66248994, 0.68792102, 0.7125342 , 0.73630021,
       0.75919081, 0.78117877, 0.80223796, 0.82234333, 0.84147098])

In [16]:
np.cos(theta)

array([1.        , 0.99940553, 0.99762282, 0.994654  , 0.99050259,
       0.98517352, 0.97867315, 0.97100919, 0.96219075, 0.95222832,
       0.94113375, 0.92892022, 0.91560226, 0.9011957 , 0.88571768,
       0.86918658, 0.85162207, 0.83304503, 0.81347755, 0.79294289,
       0.77146546, 0.74907081, 0.72578556, 0.70163739, 0.67665501,
       0.65086812, 0.62430739, 0.5970044 , 0.5689916 , 0.54030231])

In [17]:
np.sin(theta)/np.cos(theta)

array([0.        , 0.03449643, 0.06907506, 0.10381888, 0.13881245,
       0.17414278, 0.20990014, 0.24617911, 0.28307954, 0.32070776,
       0.35917787, 0.39861327, 0.43914831, 0.48093038, 0.5241222 ,
       0.56890463, 0.61547996, 0.66407597, 0.71495067, 0.7683983 ,
       0.82475655, 0.88441564, 0.94782957, 1.01553054, 1.08814714,
       1.16642801, 1.25127266, 1.34377227, 1.44526444, 1.55740772])

In [18]:
np.tan(theta)

array([0.        , 0.03449643, 0.06907506, 0.10381888, 0.13881245,
       0.17414278, 0.20990014, 0.24617911, 0.28307954, 0.32070776,
       0.35917787, 0.39861327, 0.43914831, 0.48093038, 0.5241222 ,
       0.56890463, 0.61547996, 0.66407597, 0.71495067, 0.7683983 ,
       0.82475655, 0.88441564, 0.94782957, 1.01553054, 1.08814714,
       1.16642801, 1.25127266, 1.34377227, 1.44526444, 1.55740772])

In [19]:
abs(np.array([-1,-2,3]))

array([1, 2, 3])

In [20]:
np.absolute(np.array([-1,-2,3]))

array([1, 2, 3])

In [21]:
x = np.arange(10000)

In [22]:
y = np.empty(len(x))

In [24]:
np.add(x,5,out=y)

array([5.0000e+00, 6.0000e+00, 7.0000e+00, ..., 1.0002e+04, 1.0003e+04,
       1.0004e+04])

In [25]:
y

array([5.0000e+00, 6.0000e+00, 7.0000e+00, ..., 1.0002e+04, 1.0003e+04,
       1.0004e+04])

In [26]:
np.add.reduce(x)

49995000

In [36]:
np.multiply.reduce(np.arange(2,50,dtype=np.int64))

8789267254022766592

In [37]:
arr1 = np.arange(1,10)

In [38]:
np.add.accumulate(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [39]:
np.multiply.accumulate(arr1)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [41]:
np.add.outer(arr1,arr1)

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [10, 11, 12, 13, 14, 15, 16, 17, 18]])

---